config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'users/sessions',
  }

  root 'books#index', as: 'home'

  resources :categories
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category

  validates :name, presence: true
  validates :author, presence: true
  validates :year, presence: true, numericality: { only_integer: true }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_action :authenticate_user!

  layout 'application'
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book

  def index
    @books = Book.paginate(page: params[:page])
  end

  def show; end

  def new; end

  def create
    @book.assign_attributes(book_params)

    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def edit; end

  def update
    @book.assign_attributes(book_params)

    if @book.save
      redirect_to books_path
    else
      render :edit
    end
  end

  def destroy
    @book.destroy

    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:name, :author, :year, :category_id)
  end

  def set_book
    @book ||= params[:id] ? Book.find(params[:id]) : Book.new
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category

  def index
    @categories = Category.includes(:books).paginate(page: params[:page]).order('created_at DESC')
  end

  def new; end

  def create
    @category.assign_attributes(category_params)

    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit; end

  def update
    @category.assign_attributes(category_params)

    if @category.save
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    authorize @category

    @category.destroy

    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category ||= params[:id] ? Category.find(params[:id]) : Category.new
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout 'auth'
  before_action :configure_sign_in_params, only: [:create]

  def new
    super
  end

  def create
    super
  end

  def destroy
    super
  end

  protected

  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:user, keys: [:email, :password])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/books/edit.html.erb
<nav aria-label="breadcrumb" role="navigation">
  <ol class="breadcrumb page-head-nav">
    <li class="breadcrumb-item">
      <%= link_to 'Books', books_path %>
    </li>
    <li class="breadcrumb-item active">
      Edit Book
    </li>
  </ol>
</nav>

<div class="card">
  <div class="card-header">
    Edit a Book
  </div>
  <div class="card-body">
    <%= render 'books/partials/form' %>
  </div>
</div>

app/views/books/index.html.erb
<nav aria-label="breadcrumb" role="navigation">
  <ol class="breadcrumb page-head-nav">
    <li class="breadcrumb-item active">
       Books
    </li>
  </ol>
</nav>

<div class="card card-table">
  <div class="card-header">
    <div class="row">
      <div class="col-8">
        Books List
      </div>
      <div class="col-4 text-right">
        <%= link_to 'Create a Book', new_book_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>

  <div class="card-body">
    <table class="table table-striped table-hover table-fw-widget dataTable no-footer dtr-inline">
      <thead>
        <tr>
          <th>Name</th>
          <th>Author</th>
          <th>Year</th>
          <th>Category</th>
          <th>Created at</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% if @books.any? %>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to book.name, book_path(book) %></td>
              <td><%= book.author %></td>
              <td><%= book.year %></td>
              <td><%= book.category.name %></td>
              <td><%= book.created_at.strftime('%d. %m. %y') %></td>
              <td>
                <%= link_to 'Edit', edit_book_path(book), class: 'btn btn-warning' %>
                <%= link_to 'Delete', book_path(book), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
              </td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="6" class="text-center">
              No books yet.
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= will_paginate @categories %>
  </div>
</div>

app/views/books/new.html.erb
<div class="card">
  <div class="card-header">
    Create a Book
  </div>
  <div class="card-body">
    <%= render 'books/partials/form' %>
  </div>
</div>

app/views/books/partials/_form.html.erb
<%= form_for(@book, as: :book, url: @book.persisted? ? book_path(@book) : books_path) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
  </div>

  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: 'form-control', placeholder: 'Author' %>
  </div>

  <div class="form-group">
    <%= f.label :year %>
    <%= f.text_field :year, class: 'form-control', placeholder: 'Year' %>
  </div>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.select :category_id, options_from_collection_for_select(Category.all.order(:name), :id, :name, @book.try(:category_id)), {}, { class: 'form-control' } %>
  </div>

  <%= submit_tag "Save", class: 'btn btn-primary btn-xl' %>
<% end %>

app/views/books/show.html.erb
<nav aria-label="breadcrumb" role="navigation">
  <ol class="breadcrumb page-head-nav">
    <li class="breadcrumb-item">
      <%= link_to 'Books', books_path %>
    </li>
    <li class="breadcrumb-item active">
      <%= @book.name %>
    </li>
  </ol>
</nav>

<div class="card">
  <div class="card-header">
    Book details
  </div>
  <div class="card-body">
    <dl>
      <dt>Name</dt>
      <dd><%= @book.name %></dd>
      <dt>Author</dt>
      <dd><%= @book.author %></dd>
      <dt>Year</dt>
      <dd><%= @book.year %></dd>
      <dt>Category</dt>
      <dd><%= @book.category.name %></dd>
    </dl>
  </div>
</div>

app/views/categories/edit.html.erb
<nav aria-label="breadcrumb" role="navigation">
  <ol class="breadcrumb page-head-nav">
    <li class="breadcrumb-item">
      <%= link_to 'Categories', categories_path %>
    </li>
    <li class="breadcrumb-item active">
      Edit Category
    </li>
  </ol>
</nav>

<div class="card">
  <div class="card-header">
    Edti a Category
  </div>
  <div class="card-body">
    <%= render 'categories/partials/form' %>
  </div>
</div>

app/views/categories/index.html.erb
<nav aria-label="breadcrumb" role="navigation">
  <ol class="breadcrumb page-head-nav">
    <li class="breadcrumb-item active">
      Categories
    </li>
  </ol>
</nav>

<div class="card card-table">
  <div class="card-header">
    <div class="row">
      <div class="col-8">
        Categories List
      </div>
      <div class="col-4 text-right">
        <%= link_to 'Create a Category', new_category_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>

  <div class="card-body">
    <table class="table table-striped table-hover table-fw-widget dataTable no-footer dtr-inline">
      <thead>
        <tr>
          <th>Name</th>
          <th>Nr. of books</th>
          <th>Created at</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% if @categories.any? %>
          <% @categories.each do |category| %>
            <tr>
              <td><%= category.name %></td>
              <td><%= category.books.size %></td>
              <td><%= category.created_at.strftime('%d. %m. %y') %></td>
              <td>
                <%= link_to 'Edit', edit_category_path(category), class: 'btn btn-warning' %>
                <% if policy(category).destroy? %>
                  <%= link_to 'Delete', category_path(category), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="6" class="text-center">
              No books yet.
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= will_paginate @categories %>
  </div>
</div>

app/views/categories/new.html.erb
<nav aria-label="breadcrumb" role="navigation">
  <ol class="breadcrumb page-head-nav">
    <li class="breadcrumb-item">
      <%= link_to 'Categories', new_category_path %>
    </li>
    <li class="breadcrumb-item active">
      New Category
    </li>
  </ol>
</nav>

<div class="card">
  <div class="card-header">
    Create a Category
  </div>
  <div class="card-body">
    <%= render 'categories/partials/form' %>
  </div>
</div>

app/views/categories/partials/_form.html.erb
<%= form_for(@category, as: :category, url: @category.persisted? ? category_path(@category) : categories_path) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
  </div>

  <%= submit_tag "Save", class: 'btn btn-primary btn-xl' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title></title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" type="text/css" href="lib/material-design-icons/css/material-design-iconic-font.css">

  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<div class="be-wrapper">
  <nav class="navbar navbar-expand fixed-top be-top-header">
    <div class="container-fluid">
      <div class="be-navbar-header">
        <a class="navbar-brand" href="/">
          <i class="mdi mdi-book"></i> <%= t :APP_NAME %>
        </a>
      </div>
      <div class="be-right-navbar">
        <ul class="nav navbar-nav float-right be-user-nav">
          <li class="nav-item">
            <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
          </li>
        </ul>
        <div class="page-title" id="page-title"><span></span></div>
      </div>
    </div>
  </nav>
  <div class="be-left-sidebar">
    <div class="left-sidebar-wrapper">
      <div class="left-sidebar-spacer">
        <div class="left-sidebar-scroll">
          <div class="left-sidebar-content">
            <ul class="sidebar-elements" id="main-menu">
              <li class="divider">Menu</li>
              <li class="<%= controller_name == 'books' ? 'active' : '' %>">
                <%= link_to 'Books', books_path  %>
              </li>
              <li class="<%= controller_name == 'categories' ? 'active' : '' %>">
                <%= link_to 'Categories', categories_path  %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="be-content">
    <div class="main-content container-fluid be-loading" id="main-content">
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- <link rel="shortcut icon" href="img/logo.gif"> -->
    <title></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="be-splash-screen">
    <div class="be-wrapper be-login">
      <div class="be-content">
        <div class="main-content container-fluid">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% unless object.errors.size.zero? %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button>
    <div class="icon"> <span class="mdi mdi-close-circle-o"></span></div>
    <div class="message">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>